# Generated by Django 2.2.7 on 2019-11-23 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsdJpy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time_stamp', models.CharField(max_length=128)),
                ('usd_jpy', models.CharField(max_length=128)),
            ],
        ),
    ]
